name: Multi-Servidor

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    #Forçar uso do Node.js 24 (elimina o aviso)
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante histórico completo do Git
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true  # Cache para build mais rápido
      
      - name: Instalar dependências
        run: flutter pub get
      
      - name: Compilar APK
        run: flutter build apk --release --split-per-abi
      
      - name: multi-servidor 
        uses: actions/upload-artifact@v4
        with:
          name: multi-servidor
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          retention-days: 7  # APK disponível por 7 dias
